import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import NextAuthProvider from "@/provider/naxt_auth";
import ReduxProvider from "@/provider/reduxProvider";
import ReactDND from "@/provider/react_dnd";
import Header from "@/components/Header";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <NextAuthProvider>
          <ReduxProvider>
            <ReactDND>
              <main>
                <section>{children}</section>
              </main>
            </ReactDND>
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
